### ISSUE TITLE
Track doesn't finish with a traceback

### ISSUE THREAD

**Issue by mcepl** [egh/spydaap#1]
I play a song with Rhythmbox from the server running spydaap (BTW, thank you very very much, spydaap seems to be the only DAAP server working on my RHEL-6 box), but it stops in the middle with the following in the ~/.spydaap/spydaap.log:

```
wycliff.ceplovi.cz - - [15/Jun/2014 19:03:07] "GET /databases/1/items/404.ogg?session-id=1 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.6', 32808)
Traceback (most recent call last):
  File "/usr/lib/python2.6/SocketServer.py", line 570, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 332, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/SocketServer.py", line 628, in __init__
    self.finish()
  File "/usr/lib/python2.6/SocketServer.py", line 671, in finish
    self.wfile.flush()
  File "/usr/lib/python2.6/socket.py", line 303, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by genodeftest** [comment]
In [Exaile](https://github.com/exaile/exaile), we are seeing the same issue. There is an upstream bug report against python but I can still reproduce this issue with the latest python2 builds (2.7.13): https://bugs.python.org/issue14574

See also: [exaile:plugins/daapserver/server.py:40](https://github.com/exaile/exaile/blob/master/plugins/daapserver/server.py#L40)

**Comment by egh** [comment]
Interesting. I'm not sure what is to be done, though

**Comment by genodeftest** [comment]
Probably we can only wait for upstream to fix this issue.
