### ISSUE TITLE
spydaap uses pybonjour which cannot be installed using pip because upstream is gone

### ISSUE THREAD

**Issue by genodeftest** [egh/spydaap#10]
Spydaap requires pybonjour if avahi is not present. pybonjour cannot be installed through pip, probably because its upstream is gone.

### Steps to Reproduce (for bugs)
1.  run `pip install --user pybonjour`

### Expected Behavior
Install a working copy of pybonjour.

### Current Behavior
```
$ pip install --user pybonjour
Collecting pybonjour
  Could not find a version that satisfies the requirement pybonjour (from versions: )
No matching distribution found for pybonjour
```

### Possible Solution
a) use a different Zeroconf/bonjour/mDNS implementation – there's plenty out there. Requires a fix in spydaap.

b) create our own "upstream". Requires getting the code from somewhere. Requires maintaining the code.

c) kill the dependency on pybonjour and rely on everyone having (or installing) avahi

### Additional info
This issue came up in https://github.com/egh/spydaap/pull/7#issuecomment-341946054 and was later referenced to in https://github.com/exaile/exaile/pull/445#issuecomment-342895195

avahi uses native code and may be unavailable or hard to install on Windows, MacOS and any other non-Linux platform. We may want to have a pure python implementation of Zeroconf/bonjour/mDNS.

cc'ing @virtuald

**Comment by genodeftest** [comment]
As an alternative to `pybonjour`, [`zeroconf`](https://pypi.org/project/zeroconf/) looks most promising and does not depend on any complex or native code such as bonjour, avahi or dbus. There is also an async version available, [`aiozeroconf`](https://pypi.org/project/zeroconf/). Other candidates include [mDNS](https://github.com/svinota/mdns) which is dead and [zeroconf3](https://pypi.org/project/zeroconf3/) which looks dead and has no upstream.

**Comment by virtuald** [comment]
I contacted the owner of pypi's pybonjour in November and never received a response. I sent another email, but I doubt we'll receive a response.

How does one test this anyways? Looking at the code, it seems like migration to zeroconf should be trivial. However, zeroconf has dropped python 2 support, so would need to have a conditional in setup.py

**Comment by genodeftest** [comment]
zeroconf python 2 version is still available and can be installed through pip. See https://github.com/jstasiak/python-zeroconf/commit/f22f421e4e6bf1ca7671b1eb540ba09fbf1e04b1#comments for details. It just doesn't get any bug fixes any more but anyone should migrate to python 3 anyway.
