### ISSUE TITLE
Push this package to pypi?

### ISSUE THREAD

**Issue by virtuald** [egh/spydaap#6]
It would make it easier for other python projects to use, and make it easier for users to install it (`pip install spydaap`). It's pretty simple, let me know if you need help setting it up.

**Comment by virtuald** [comment]
I've taken the liberty to bump the version and push a package to pypi for this project. This will make it easier for our project's users to install spydaap.

However, if you wish to maintain a package on pypi, I'm certainly happy to relinquish the pypi package to you -- your pypi username and I will transfer ownership. Otherwise, we will continue to maintain our friendly fork and push updates as they become available.

**Comment by egh** [comment]
@virtuald Thanks, I'm happy to have you do this :) I'm not using this package at the moment, so I don't have much time to work on this. Thanks again!
